Repository dgidb/dgidb-v5, pull requests merged in 2024-06, with the labels that each got.

#506 docs: update overview
  client/src/pages/About/SubSections/Overview.tsx
Labels: priority:low

#497 feat: make gene claim category search case-insensitive
  server/app/graphql/resolvers/genes.rb
Labels: priority:low, backend

#500 feat: make 404 page global error page and have unrecognized paths rou…
  client/src/components/Drug/DrugRecord/DrugRecord.tsx
  client/src/components/Gene/GeneRecord/GeneRecord.tsx
  client/src/components/Interaction/InteractionRecord/InteractionRecord.tsx
  client/src/components/Shared/NotFoundError/NotFoundError.tsx
  client/src/routes/public.tsx
Labels: frontend, priority:low

#503 chore: remove unused code and add linting and pre-commit hooks
  README.md
  client/.eslintrc.js
  client/.husky/pre-commit
  client/.pre-commit-config.yaml
  client/package.json
  client/src/components/About/InteractionClaimTypes/TypesTable.tsx
  client/src/components/Browse/Categories/BrowseCategories.scss
  client/src/components/Browse/Categories/BrowseCategories.tsx
  client/src/components/Browse/Sources/BrowseSources.tsx
  client/src/components/Drug/DrugCharts/DirectionalityDrug.tsx
  client/src/components/Drug/DrugRecord/DrugRecord.tsx
  client/src/components/Drug/DrugSearchResults/DrugSearchResults.scss
  client/src/components/Drug/DrugSearchResults/DrugSearchResults.tsx
  client/src/components/Drug/DrugSummary/DrugSummary.scss
  client/src/components/Drug/DrugSummary/DrugSummary.tsx
  client/src/components/Gene/GeneCharts/DirectionalityGene.tsx
  client/src/components/Gene/GeneRecord/GeneRecord.tsx
  client/src/components/Gene/GeneSearchResults/GeneSearchResults.scss
  client/src/components/Gene/GeneSearchResults/GeneSearchResults.tsx
  client/src/components/Gene/GeneSummary/GeneSummary.scss
  client/src/components/Gene/GeneSummary/GeneSummary.tsx
  client/src/components/GeneCategories/AmbiguousMatchCard/AmbiguousMatchCard.tsx
  client/src/components/GeneCategories/AmbiguousMatches/AmbiguousMatches.tsx
  client/src/components/GeneCategories/DirectMatchCard/DirectMatchCard.tsx
  client/src/components/GeneCategories/DirectMatches/DirectMatches.tsx
  client/src/components/GeneCategories/GeneCategoriesSearchResults/GeneCategoriesSearchResults.tsx
  client/src/components/Interaction/InteractionRecord/InteractionRecord.tsx
  client/src/components/Layout/MainLayout.scss
  client/src/components/Shared/AmbiguousTermsSummary/AmbiguousResult.tsx
  client/src/components/Shared/Buttons/ButtonAction.tsx
  client/src/components/Shared/ErrorMessage/ErrorMessage.tsx
  client/src/components/Shared/NotFoundError/NotFoundError.tsx
  client/src/components/Shared/ReleaseInformation/ReleaseInformation.tsx
  client/src/components/Shared/SearchBar/SearchBar.tsx
  client/src/components/Shared/TabPanel/TabPanel.tsx
  client/src/pages/API/API.tsx
  client/src/pages/Browse/Browse.tsx
  client/src/routes/public.tsx
  client/yarn.lock
Labels: frontend, priority:low, technical debt, cleanup

#499 fix: exclude factors from unique gene name check in MPs
  server/lib/genome/importers/api_importers/civic/api_client.rb
  server/lib/genome/importers/api_importers/civic/importer.rb
Labels: bug, priority:low

#510 added row for Dec 2023 dumps
  client/src/pages/Downloads/Files/Files.tsx
Labels: priority:high
